### ISSUE TITLE
state对象下的值无法响应mutations

### ISSUE THREAD

**Issue by artiely** [wangdahoo/map-state-vmodel#1]
state对象下的值似乎没有响应mutations,如示例中form下的值，我尝试了，userName起作用但是form下的值不起作用，README中没有此示例是目前没有实现吗？

**Comment by wangdahoo** [comment]
参考下本项目 webapp 下的代码 @artiely

**Comment by artiely** [comment]
我是看了webapp的代码，好像必须使用namespace,与现有代码还是有些不兼容；https://github.com/maoberlehner/vuex-map-fields，所以我选择了他。
